// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8oAUehq-UYW_E8eDBAR_yKyFy5ValVfM',
    appId: '1:454294255294:web:57d3a42220a9e5b6eb10ef',
    messagingSenderId: '454294255294',
    projectId: 'binimoy-v1',
    authDomain: 'binimoy-v1.firebaseapp.com',
    storageBucket: 'binimoy-v1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHEsM9bC3jieRoxDCU3aYRZ1z4KsqQ7mI',
    appId: '1:454294255294:android:0d3f86e9c7e35b57eb10ef',
    messagingSenderId: '454294255294',
    projectId: 'binimoy-v1',
    storageBucket: 'binimoy-v1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOc__bkZaEqeQ2w0fCGIYmYooUMjZJk3c',
    appId: '1:454294255294:ios:3ac9b5a35744c53deb10ef',
    messagingSenderId: '454294255294',
    projectId: 'binimoy-v1',
    storageBucket: 'binimoy-v1.firebasestorage.app',
    iosBundleId: 'com.example.binimoy',
  );
}
